Appets.WebUI/Models/MascotasViewModel.cs
using Appets.DataAccess.Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Appets.WebUI.Models
{
    public class MascotasViewModel
    {

        //[HiddenInput]
        //public int masc_Id { get; set; }

        //[Display]
        //[Required(ErrorMessage = "Seleccione una imagen de su computadora.")]
        //public IFormFile ImageFile { get; set; }

        public AccionMascota AccionMascota { get; set; }
        public CambiarImagen CambiarImagen { get; set; }

        public MascotasViewModel()
        {
            CambiarImagen = new CambiarImagen();
            AccionMascota = new AccionMascota();
        }


    }

    public class CambiarImagen
    {
        [HiddenInput]
        public int masc_Id { get; set; }
        public string MascotaPriview { get; set; }

        public string nombreMascota { get; set; }
        [Display]
        [Required(ErrorMessage = "Seleccione una imagen de su computadora.")]
        public IFormFile ImageFile { get; set; }
    }

    public class AccionMascota
    {

       
        [Display(Name = "Id")]
        public int? masc_Id { get; set; }

        [Display(Name = "Foto")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Imagen { get; set; }

        [Display(Name = "Nombre Mascota")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Nombre { get; set; }

        [Display(Name = "Especie")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int espc_Id { get; set; }
        public SelectList Especielist { get; set; }

        [Display(Name = "Raza")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int raza_Id { get; set; }
        public SelectList Razalist { get; set; }

        [Display(Name = "Edad")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int masc_Edad { get; set; }


        [Display(Name = "Sexo")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Sexo { get; set; }


        [Display(Name = "Peso")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Peso { get; set; }

        [Display(Name = "Talla")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Talla { get; set; }


        [Display(Name = "Color")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_Color { get; set; }

        [Display(Name = "Empleado")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int emp_Id { get; set; }

        public SelectList Empleadolist { get; set; }
        [Display(Name = "Es Adoptado")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public bool masc_EsAdoptado { get; set; }


        [Display(Name = "Es Reservado")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public bool masc_EsReservado { get; set; }


        [Display(Name = "Historial")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public string masc_HistorialDescripcion { get; set; }


        [Display(Name = "Procedencia")]
        [Required(ErrorMessage = "El campo {0} es requerido")]
        public int proc_Id { get; set; }
        public SelectList Procedencialist { get; set; }



        public void LlenarListas(IEnumerable<tbEspecies> especies)
        {
            Especielist = new SelectList(especies, "espc_Id", "espc_Descripcion");
        }

        public void LlenarListas(IEnumerable<UDP_tbRazas_SelectResult> razas)
        {
            Razalist = new SelectList(razas, "raza_Id", "raza_Descripcion");
        }

        public void LlenarListas(IEnumerable<UDP_tbPersonas_EsEmpleadoResult> personas)
        {
            Empleadolist = new SelectList(personas, "per_Id", "per_Nombres");
        }

        public void LlenarListas(IEnumerable<tbProcedencia> procedencias)
        {
            Procedencialist = new SelectList(procedencias, "proc_Id", "proc_Descripcion");
        }
    }






 
}

Appets.WebUI/Controllers/MascotasController.cs
using Appets.DataAccess.Entities;
using Appets.DataAccess.Repositories;
using Appets.DataAccess.Services;
using Appets.WebUI.Attribute;
using Appets.WebUI.Extensions;
using Appets.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Appets.WebUI.Controllers
{
    public class MascotasController : BaseController
    {

        private readonly MascotasRepository _mascotasRepository;
        private readonly EspeciesRepository _especiesRepository;
        private readonly RazasRepository _razasRepository;
        private readonly ProcedenciaRepository _procedenciaRepository;
        private readonly PersonaRepository _personaRepository;
        private readonly HelpersServicie _helpersServicie;


        public MascotasController(
            MascotasRepository mascotasRepository,
            EspeciesRepository especiesRepository, 
            RazasRepository razasRepository,
            ProcedenciaRepository procedenciaRepository,
            PersonaRepository personaRepository,
            HelpersServicie helpersServicie)
        {
            _mascotasRepository = mascotasRepository;
            _especiesRepository = especiesRepository;
            _razasRepository = razasRepository;
            _procedenciaRepository = procedenciaRepository;
            _personaRepository = personaRepository;
            _helpersServicie = helpersServicie;
        }

        //[SessionManager("Listado Mascotas")]
        public IActionResult Index()
        {
            var model = new MascotasViewModel();
            model.AccionMascota.LlenarListas(_especiesRepository.EspeciesList());
            model.AccionMascota.LlenarListas(_razasRepository.RazasList());
            model.AccionMascota.LlenarListas(_personaRepository.PersonaListado5());
            model.AccionMascota.LlenarListas(_procedenciaRepository.ProcedenciaList());

            return View(model);

        }


      
        public IActionResult Eliminar(int id)
        {
            var result = _mascotasRepository.Delete(id);
            return Json(result);
        }


        public IActionResult RazasList(int id) 
        {
            var resultado = _razasRepository.RazasByEspecie(id);
            return Json(resultado);
        }


        public IActionResult CambiarImagen(CambiarImagen model)
        {
            if (ModelState.IsValid)
            {
                var result = _helpersServicie.updateMascotasImagen(model.ImageFile, model.masc_Id);
                ShowAlert("Imagen Guardada correctamente",AlertMessageType.Success );
               
            }
            else
            {
                ShowAlert("Ha ocurrido un error", AlertMessageType.Error);
            }


            return RedirectToAction("Index");
        }

        //[SessionManager("Listado Mascotas")]
        public IActionResult AgregarMascotas()
        {
           
           
            var model = new MascotasViewModel();
            model.AccionMascota.LlenarListas(_especiesRepository.EspeciesList());
            model.AccionMascota.LlenarListas(_razasRepository.RazasList());
            model.AccionMascota.LlenarListas(_personaRepository.PersonaListado5());
            model.AccionMascota.LlenarListas(_procedenciaRepository.ProcedenciaList());
            ViewBag.masc_Id = 0;
            return View(nameof(MascotaAccion), model);
            
        }

        public ActionResult ListarMascotas()
        {
           
            IEnumerable<UDP_tbMascotas_SelectResult> lista = _mascotasRepository.MascotasList();

            return Json(new
            {

                data = lista.Select(x => new
                {
                    masc_Id = x.masc_Id,
                    //masc_Imagen = x.masc_Imagen,
                    masc_Nombre = x.masc_Nombre,
                    espc_Id = x.espc_Descripcion,
                    raza_Id = x.raza_Descripcion,
                    //masc_Edad = x.masc_Edad,
                    masc_Sexo = x.masc_Sexo,
                    masc_Peso = x.masc_Peso,
                    //masc_Talla = x.masc_Talla,
                    masc_Color = x.masc_Color,
                    //emp_Id = x.emp_Id,
                    masc_EsAdoptado = x.masc_EsAdoptado,
                    masc_EsReservado =  x.masc_EsReservado,
                    //masc_HistorialDescripcion = x.masc_HistorialDescripcion,
                    proc_Id = x.proc_Descripcion

                })
                .OrderBy(x => x.masc_Id)
            });
        }


        public IActionResult updateMascotasImagen(AccionMascota model)
        {

            if (ModelState.IsValid)
            {
                var result = new tbMascotas();

                ViewBag.masc_Id = model.masc_Id;
                ViewBag.masc_Imagen = model.masc_Imagen;
                //result = _mascotasRepository.updateMascotasImagen1(model.masc_Nombre, ViewBag.masc_Id);
                if (result == null)
                {
                    ShowAlert("Imagen Actualizada Correctamente", AlertMessageType.Success);
                    return RedirectToAction("Index");

                }

                else
                {

                    goto error;
                }

            error:
                model.masc_Id = 0;
                ViewBag.masc_Id = 0;

                ShowAlert("Error.", AlertMessageType.Error);
                return View(model);

            }

            return RedirectToAction("Index");
        }


        //[SessionManager("Crear Mascotas")]
      
        //[HttpPost("mascotas/listado-mascotas", Name = "SaveMascota")]

        public IActionResult MascotaAccion(AccionMascota model)
        {


            //if (ModelState.IsValid)
            //{
                int result = 0;
                ViewBag.masc_Id = model.masc_Id;
                if (model.masc_Id == 0)
                {

                    result = _mascotasRepository.Insert(
                        model.masc_Imagen,
                        model.masc_Nombre,
                        model.espc_Id,
                        model.raza_Id,
                        model.masc_Edad, 
                        model.masc_Sexo, 
                        model.masc_Peso,
                        model.masc_Talla,
                        model.masc_Color,
                        model.emp_Id,
                        //model.masc_EsAdoptado,
                        //model.masc_EsReservado,
                        model.masc_HistorialDescripcion,
                        model.proc_Id);
                    if (result != -1)
                    {
                        ShowAlert("Registro Ingresado Correctamente", AlertMessageType.Success);
                        return RedirectToAction(nameof(MascotaFind),new {id = model.masc_Id});
                        
                    }

                    else
                    {

                        goto error;
                    }

                }
                else
                {
                    result = _mascotasRepository.update(
                        ViewBag.masc_Id,
                        model.masc_Nombre,
                        model.espc_Id,
                        model.raza_Id,
                        model.masc_Edad,
                        model.masc_Sexo,
                        model.masc_Peso,
                        model.masc_Talla,
                        model.masc_Color,
                        model.emp_Id,
                        //model.masc_EsAdoptado,
                        //model.masc_EsReservado,
                        model.masc_HistorialDescripcion,
                        model.proc_Id);
                    if (result != -1)
                    {
                        ShowAlert("Registro actualizado Correctamente", AlertMessageType.Success);
                        return RedirectToAction("Index");

                    }
                    else
                    {

                        goto error;
                    }
                }
            error:
                model.masc_Id = 0;
                ViewBag.masc_Id = 0;
               

                ShowAlert("Ingrese un Registro", AlertMessageType.Info);
                return View(model);

            //}
            //return RedirectToAction("Index");


        }

        //public string SplitVirgulilla(string param)
        //{
        //     param.Replace("~", string.Empty);

        //}
        //[SessionManager("Editar Mascotas")]
        public IActionResult MascotaFind(int id)
        {
            var mascotas = _mascotasRepository.Find(id);
            if (mascotas == null)
            {
                return View(nameof(Index));
            }

            var model = new MascotasViewModel();
            ViewBag.masc_Id = id;
            model.CambiarImagen.masc_Id = id;
            model.CambiarImagen.MascotaPriview = mascotas.masc_Imagen;
            model.AccionMascota.masc_Imagen = mascotas.masc_Imagen;
            model.AccionMascota.masc_Nombre = mascotas.masc_Nombre;
            model.AccionMascota.espc_Id = mascotas.espc_Id;
            model.AccionMascota.raza_Id = mascotas.raza_Id;
            model.AccionMascota.masc_Edad = mascotas.masc_Edad;
            model.AccionMascota.masc_Sexo = mascotas.masc_Sexo;
            model.AccionMascota.masc_Talla = mascotas.masc_Talla;
            model.AccionMascota.masc_Color = mascotas.masc_Color;
            model.AccionMascota.emp_Id = mascotas.emp_Id;
            model.AccionMascota.masc_Peso = mascotas.masc_Peso;
            model.CambiarImagen.nombreMascota = mascotas.masc_Nombre;
            //model.AccionMascota.masc_EsAdoptado = mascotas.masc_EsAdoptado;
            //model.AccionMascota.masc_EsReservado = mascotas.masc_EsReservado;
            model.AccionMascota.masc_HistorialDescripcion = mascotas.masc_HistorialDescripcion;

Appets.WebUI/Views/Mascotas/ImagenMascotaPartial.cshtml
@model CambiarImagen


    <style>
            #img {
                display: block;
                margin-left: auto;
                margin-right: auto;
                width: 200px;
                height: 200px;
               border-radius: 150px;
                border: 2px solid #666;
            }

            #lblImageFile {
                border: 2px solid #666;
            }

            .custom-file-input {
                background-color: springgreen;
            }

            .card {
                background-color: lavender;
            }
        p.texto {
            text-align: center;
            font-size: 2em;
            font-weight: 500;
            font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        }
      
    </style>
<div class="card" style="max-width:70%">
    <div class="card-header" style="background-color: lightgrey;max-height:30%">
        <a style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:1em;font-weight: 600; "> <img class="img-fluid" alt="camara image" src="~/images/camera.png" />  Perfil de Mascota </a>
    </div>
    <form asp-controller="Mascotas" asp-action="CambiarImagen" method="post" enctype="multipart/form-data">
        <input id="masc_Id" type="hidden" asp-for="masc_Id" />
        <div class="card-body">

            <p class="text-muted small">Actualize la foto de la mascota.</p>
            <div>
                <img src="@Model.MascotaPriview" height="200" alt="" id="img" >
                
            </div>
            <p class="texto">@Model.nombreMascota</p>
            <div class="row">
                <div class="col-sm-9">
                    <br />
                    <p>Seleccione una imagen(.jpg, .png, gif)con un tamaño menor de 2MB(2,048 KB).</p>
                    <div class="custom-file">
                        <input asp-for="ImageFile" type="file" class="custom-file-input"  onchange="previewFile()" id="file"/>
                        <label id="lblImageFile" asp-for="ImageFile" class="custom-file-label" accept="imagen/png, imagen/jpeg, imagen/gif">Seleccione una imagen.....</label>

                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                       
                    </div>
                </div>
               
            </div>
        </div>
        <div class="card-footer" style="background-color:skyblue;">
            <button type="submit" class="btn btn-raised btn-primary">
                <i class="mdi mdi-refresh"></i><span>@(Model.masc_Id> 0 ? "Cambiar Imagen":"Guardar Imagen")</span>
            </button>
            <a style="background-color:gray;color:white" asp-controller="Mascotas" asp-action="Index" class="btn btn-secundary">Cancelar</a>
        </div>
    </form>

</div>


<script type="text/javascript">
        //extensiones de las imagenes
        var extensionesPermitidas = /(.png|.jpg|.jpge|.PNG|.JPG|.JPGE)$/i;

        function previewFile() {
            //se pasa el 'img' a una variable
            var preview = document.getElementById('img');
            //se para el archivo seleccionado a una variable
            var file = document.getElementById('file').files[0];
            //se obtiene la direccion de la imagen
            var archivoRuta = document.getElementById('file').value;

            //validacion de la extension de la imagen
            if (!extensionesPermitidas.exec(archivoRuta)) {
                alert('Extension del archivo no valida');
                document.getElementById('file').value = '';
                return false;
            }
            else {
                //El FileReader permite leer los ficheros almacenados en el cliente
                var reader = new FileReader();

                //onloadend: es un EventHandler que representa el código cuando el progreso se ha detenido en la carga de un recurso.
                reader.onloadend = function () {
                    //se accede al src del <img> y se agrega la direccion
                    preview.src = reader.result;
                }

                if (file) {
                    //es usado para leer el contenido del especificado File
                    reader.readAsDataURL(file);
                } else {
                    preview.src = "";
                }
            }

        }
</script>

Appets.WebUI/Views/Mascotas/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-10"><h3 style="font-family: Nunito,sans-serif; font-size:1.1em;font-weight: 600;">Listado de mascotas</h3></div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-striped dt-responsive nowrap " id="datatable">

            <thead style="background-color:mediumpurple" class="text-center  text-white">
                <tr>
                    <th>Id</th>
                    @*<th>Imagen</th>*@
                    <th>Nombre</th>
                    <th>Especie</th>
                    <th>Raza</th>
                    <th>Sexo</th>
                    <th>Color</th>
                    <th>Adoptado</th>
                    <th>Reservado</th>
                    <th>Acciones</th>
                </tr>
            </thead>
        </table>

    </div>
</div>


<div class="modal fade" tabindex="-1" id="ModalEliminar" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Eliminar Mascota</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <input type="hidden" id="ID" />
                            <p>¿Esta seguro que desea eliminar el registro?</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-outline-danger" onclick="Eliminar()">Confirmar</button>
            </div>
        </div>
    </div>
</div>




@section Scripts{

    <script src="~/js/Catalogo/list/list-mascotas.js"></script>
    <script src="~/js/Catalogo/llenar-dropdow-list.js"></script>
    <script>
        appConfig.Mascotas.configureTable({ listUrl: "@Url.Action("ListarMascotas")" });
    </script>
}

Appets.WebUI/Views/Mascotas/MascotaAccion.cshtml
@model MascotasViewModel

@{
    ViewData["Title"] = "Mascotas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-6">
        <partial name="MascotaAccionPartial" model="@Model.AccionMascota">
    </div>

    @if (Model.CambiarImagen.masc_Id > 0)
    {
        <div class="col-md-6">
            <partial name="ImagenMascotaPartial" model="@Model.CambiarImagen">
        </div>
    }

</div>

Appets.WebUI/Views/Mascotas/MascotaAccionPartial.cshtml
@model AccionMascota



<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <style>
        .control-label {
            font-family: 'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
            font-size: 1.1em;
        }
    </style>
</head>

<form asp-action="MascotaAccion" method="post">
    <div class="col-12">
        <div class="card">
            <div class="card-header" style="background-color: lightgrey;max-height:30%">
                <a style="font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size:1em;font-weight: 600; "> <img class="img-fluid" alt="macota image" src="~/images/pets.png" /> Registro de Mascotas </a>

            </div>
            <div class="card-body">
                <input type="hidden" id="masc_Id" asp-for="masc_Id" value="@ViewBag.masc_Id" />
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label">Nombre Mascota</label>
                                <input class="form-control" asp-for="masc_Nombre" id="masc_Nombre" type="text" maxlength="13" required />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>

                    </div>


                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label">Especie</label>
                                <select asp-for="espc_Id" class="form-control" id="DropEspecie" asp-items="Model.Especielist">
                                    <option>Seleccione una opcion</option>
                                </select>
                                <span class="text-danger" asp-validation-for="espc_Id" id="ErrorMessage"></span>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label asp-for="raza_Id" class="control-label"></label>
                                <select asp-for="raza_Id" class="form-control" id="DropRaza">
                                    <option>Seleccione una raza</option>
                                </select>
                                <span class="text-danger" asp-validation-for="raza_Id"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Sexo</label>
                                <input class="form-control" asp-for="masc_Sexo" id="masc_Sexo" type="text" maxlength="50" required />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>
                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Edad</label>
                                <input class="form-control" asp-for="masc_Edad" id="masc_Edad" type="text" maxlength="50" />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>

                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Procedencia</label>
                                <select asp-for="proc_Id" class="form-control" asp-items="Model.Procedencialist">
                                    <option>Seleccione una opcion</option>
                                </select>
                                <span class="text-danger" asp-validation-for="proc_Id" id="ErrorMessage"></span>
                            </div>
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Peso</label>
                                <input class="form-control" asp-for="masc_Peso" id="masc_Peso" type="text" maxlength="50" />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>
                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Talla</label>
                                <input class="form-control" asp-for="masc_Talla" id="masc_Talla" type="text" maxlength="8" required />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>

                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Color</label>
                                <input class="form-control" asp-for="masc_Color" id="masc_Color" type="text" maxlength="8" required />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>
                    </div>



                    <div class="row">

                        <div class="col-md-12">

                            <div class="form-group">
                                <label class="control-label">Nombre Empleado</label>
                                <select asp-for="emp_Id" class="form-control" asp-items="Model.Empleadolist">
                                    <option>Seleccione una opcion</option>
                                </select>
                                <span class="text-danger" asp-validation-for="emp_Id" id="ErrorMessage"></span>
                            </div>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col-md-12 ">
                            <div class="form-group">
                                <label class="control-label">Historial</label>
                                <textarea class="form-control" asp-for="masc_HistorialDescripcion" id="masc_HistorialDescripcion" maxlength="100" type="text"></textarea>
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>


                    </div>
                    @if (Model.masc_Id > 0)
                    {
                        <div class="col-md-4 ">
                            <div class="form-group">
                                <label class="control-label">Es Adoptado</label>
                                <input class="form-control" asp-for="masc_EsAdoptado" id="masc_EsAdoptado" type="checkbox" />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="control-label">Es Reservado</label>
                                <input class="form-control" asp-for="masc_EsReservado" id="masc_EsReservado" type="checkbox" maxlength="8" required />
                                <span class="text-danger" id="ErrorMessage"></span>
                            </div>
                        </div>
                    }
                    else
                    {

                    }


                    <div class="form-group row m-t-20">
                        <div class="col-12">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button class="btn btn-raised btn-primary"><i class="mdi mdi-content-save"></i><span>@(Model.masc_Id > 0 ? "Guardar Cambios" : "Guardar")</span></button>
                            <a style="background-color:gray;color:white" asp-controller="Mascotas" asp-action="Index" class="btn btn-secundary">Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>






@section Scripts{

    <script>
        $(document).ready(function () {
            console.log("hola");
        })
        $('#DropEspecie').change(function () {
            var especie = $(this).val();
            console.log(especie);
            $('#DropRaza').empty();
            $('#DropRaza').append('<option>Seleccione una raza</option>');
            $.getJSON("/Mascotas/RazasList/" + especie, function (data) {
                $.each(data, function (key, value) {
                    $('#DropRaza').append('<option value="' + value.raza_Id + '">' + value.raza_Descripcion + '</option>');
                });
            });
        })
    </script>
    <script src="~/js/Catalogo/llenar-dropdow-list.js"></script>
}